title: Normale Seite
icon: page

tabs:
  # content tab
  content:
    label: Inhalt
    icon: layers
    sections:
      content:
        type: fields
        fields:
          contentlabel:
            type: headline
            label: Content
          layout:
            extends: fields/layout
  #subpages
  subpages:
    label: Subpages
    icon: layers
    sections:
      pages:
        extends: sections/pages
        templates:
          - default

  # gallery tab
  gallery:
    extends: tabs/galleryTab

  # misc
  misc:
    extends: tabs/miscTab   
  # metaknight
  seotab:
    extends: seo
    label: SEO