title: Default Image

accept:
  mime: image/*
  type: image
  maxsize: 6000000

fields:
  alt:
    label: Alt Text
    type: text
    width: 1/2
  caption:
    label: Caption
    type: textarea
    width: 1/2
