title: Site

tabs:
  # pages tab
  pages:
    label: Workshops/Seiten
    icon: layers
    columns:
      - width: 2/3
        sections:
          stats: sections/statsSite
          groups:
            extends: sections/pages
            headline: Workshop-Räume
            search: true
            type: pages
            layout: table
            image: false
            sortBy: dateCreatedEpoch desc
            info: false
            columns:
              exhibitions:
                label: Ausstellungen
                type: text
                width: 1/9
                value: "{{page.children.filterBy('intendedTemplate','c_exhibition').count}}"
              exhibits:
                label: Objekte
                type: text
                width: 1/11
                value: "{{page.children.filterBy('intendedTemplate','c_exhibit').count}}"
              datecreatedepoch:
                label: Angelegt
                type: text
                width: 1/8
                value: "{{ page.dateCreatedEpoch.epoch2date('yyyy.MM.dd') }}"
              clean:
                label: Cleaned
                type: html
                width: 1/10
                value: <div class="isDone isDone-{{page.clean}}">Cleaned</div>
              complete:
                label: Abgegeben
                type: html
                width: 1/9
                value: <div class="isDone isDone-{{page.complete}}">Abgegeben</div>
            templates:
              - c_workshop
      - width: 1/3
        sections:
          pages:
            extends: sections/pages
            headline: Reguläre Seiten
            type: pages
            templates:
              - home
              - default
              - loadmore
              - materials
              - legal
              - login
              - error
            create:
              - default
              - legal
              - loadmore
            image:
              query: false
              back: white
  # content settings
  content_settings:
    label: Content Einstell.
    icon: settings
    columns:
      - width: 1/2
        sections:
          data_populators:
            extends: sections/pages
            headline: Daten für Felder
            help: Sie können unterschiedliche Daten-Sets anlegen, z.B. wenn Sie neue Daten für die Dropdowns und Co. testen wollen (Zugehörigkeiten, Klassifikation, etc)
            type: pages
            templates:
              - d_structures
          data_fieldinfos:
            extends: sections/pages
            headline: Beschritungen und Nachrichten
            help: Sie können unterschiedliche Informationen-Sets anlegen, z.B. wenn Sie neue Beschriftungen testen wollen.
            type: pages
            templates:
              - d_labelinfos
          # data_usernames:
          #   extends: sections/pages
          #   headline: Benutzernamen
          #   type: pages
          #   templates:
          #     - d_usernames
      - width: 1/2
        sections:
          data_fields:
            headline: Daten Felder
            type: fields
            fields:
              data_populators_pick:
                type: pages
                label: Aktive "Daten für Felder"
                help: Hier wählen Sie den aktiven Daten-Set aus.
                max: 1
                query: site.children.filterBy('intendedTemplate', 'd_structures')
              data_fieldinfos_pick:
                type: pages
                label: Aktive "Beschritungen und Nachrichten"
                help: Hier wählen Sie den aktiven Informationen-Set aus.
                max: 1
                query: site.children.filterBy('intendedTemplate', 'd_labelinfos')
              # data_usernames_pick:
              #   type: pages
              #   label: Aktive "Benutzernamen"
              #   max: 1
              #   query: site.children.filterBy('intendedTemplate', 'd_usernames')

  # settings tab
  settings:
    label: Website Einstell.
    icon: settings
    sections:
      headersettings:
        type: fields
        fields:
          
          # header
          hglobal:
            label: Header Information
            type: headline
          institutionlogo:
            label: Logo Museum
            type: files
            multiple: false
            translate: false
            width: 1/4
            max: 1
            layout: list
            image:
              back: white
          projectlogo:
            label: Logo Projekt
            type: files
            multiple: false
            translate: false
            width: 1/4
            max: 1
            layout: list
            image:
              back: white

          # workshops
          wsglobal:
            label: Workshop-Bereich
            type: headline
          usertimeouttime:
            label: Dauer bis Auto-Logout
            type: number
            width: 1/3
            after: Minuten
            min: 0.5
            max: 40
            default: 20
            required: true
            help: 'min: 0.5, max: 40'
          lockedpagestime:
            label: Dauer der Seitensperre (Ausstellungen)
            type: number
            after: Minuten
            width: 1/3
            min: 0.5
            max: 20
            default: 10
            required: true
            help: 'min: 0.5, max: 20'

          # mailing
          hemailsettings:
            label: Email Information
            type: headline
          from_address:
            label: Absender (generierte Emails)
            type: email
            help: "Absender aller generierten Emails, z.B. jds@dah.com. ACHTUNG: bitte je nach Server sicher stellen, dass diese Adresse Emails versenden darf."
          to_address:
            label: Empfänger (generierte Emails)
            type: email
            width: 1/2
            help: Empfänger aller generierten Emails, z.B. workshops@dah.com
          cc_address:
            label: CC Empfänger (generierte Emails)
            type: email
            width: 1/2
            help: CC Empfänger aller generierten Emails, z.B. admin@2av.de
          mail_subject:
            label: Betreff
            type: text
            help: Betreff für generierte Emails, z.B. "Ein neuer Workshop wurde fertig gestellt"

          # system
          fglobal:
            label: System
            type: headline
          janitorclean:
            type: janitor
            label: Workshops bereinigen
            generator: false
            width: 1/3
            progress: Bitte warten ...
            job: cleanroutine
          janitorusersdeac:
            type: janitor
            label: Benutzer deaktivieren
            generator: false
            width: 1/3
            progress: Bitte warten ...
            job: deactivateusers
          janitorusersdelete:
            type: janitor
            label: Inaktive Benutzer löschen
            generator: false
            width: 1/3
            progress: Bitte warten ...
            job: deleteusers
          systemline1:
            type: line
          uservaliditydate:
            type: number
            width: 1/3
            required: true
            min: 7
            max: 40
            default: 30
            after: Tage
            label: Default Gültigkeit der temporären Kontos
            help: 'min: 7, max: 40'
          userdaysbeforedelete:
            type: number
            width: 1/3
            required: true
            min: 7
            max: 60
            default: 40
            after: Tage
            label: Default Dauer bis zum Löschen des inaktiven temporären Kontos
            help: 'min: 7, max: 60'

  # gallery tab
  gallery:
    extends: tabs/galleryTab

    # metaknight
  seotab: seo

  # help tab
  #help:
  # extends: tabs/helpTab
